### ISSUE TITLE
Feature request: `plot(fg, :x0)`

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/RoMEPlotting.jl#10]
Which would simplify Julia broadcasts as follows:
```julia
plot.(fg, [:l1, :l2, :l3])
```

Current closest matches are:
```
drawPoses
drawPosesLandms
drawLandms
```

but these functions see out of line with convenience `plot` for 2D and `draw` for 3D.

**Comment by pvazteixeira** [comment]
Today's steps in that direction
 - [`plotKDE`](https://github.com/JuliaRobotics/RoMEPlotting.jl/blob/70c70d045283046e830d52e1514f403d3880eb98/src/RobotViz.jl#L442)
 - [`plotKDE`](https://github.com/JuliaRobotics/RoMEPlotting.jl/blob/70c70d045283046e830d52e1514f403d3880eb98/src/RobotViz.jl#L446)

**Comment by dehann** [comment]
That's close enough for now I think -- thanks for adding!

**Comment by dehann** [comment]
also see #8
