### ISSUE TITLE
plotCliqUpMsgs Error

### ISSUE THREAD

**Issue by lemauee** [JuliaRobotics/RoMEPlotting.jl#133]
Hi,

 similar to `plotCliqDownMsgs` #131,  `plotCliqUpMsgs` also seems to be using functions that do not exist (anymore).

```julia
ERROR: UndefVarError: getUpMsgs not defined
Stacktrace:
 [1] getTreeCliqUpMsgsAll(::BayesTree) at /home/leopold/.julia/packages/IncrementalInference/JEqfk/src/TreeMessageUtils.jl:480
 [2] plotCliqUpMsgs(::LightDFG{SolverParams,DFGVariable,DFGFactor}, ::BayesTree, ::Symbol; show::Bool, dims::Array{Int64,1}, levels::Int64, c::Nothing, title::String) at /home/leopold/.julia/packages/RoMEPlotting/2IvGD/src/SolverVisualization.jl:951
 [3] plotCliqUpMsgs(::LightDFG{SolverParams,DFGVariable,DFGFactor}, ::BayesTree, ::Symbol) at /home/leopold/.julia/packages/RoMEPlotting/2IvGD/src/SolverVisualization.jl:951
 [4] top-level scope at  none:1
```
Best,
Leo

**Comment by dehann** [comment]
Hi Leo,

Apologies for missing this one too.  We've been on break for a bit and should be coming back on line now.  This might be related to JuliaRobotics/IncrementalInference.jl#1053 that was recently fixed.  We will check and restore this function and also make sure this is added to testing.

Also note latest versions are RoMEPlotting v0.5.1, RoME.jl v0.12.0, IIF v0.20.2

@Affie , could you perhaps help with this issue please.

**Comment by Affie** [comment]
Sure, I'll have a look. I kind of remember fixing this, but it might have been a similar function.

**Comment by Affie** [comment]
Sorry, it took a bit longer to get to it than expected, but it's updated now. It will need new IIF (v0.21.1). If its really needed we can backport fixes, but the rest of the packages should soon be compatible with IIF v0.21

**Comment by lemauee** [comment]
Backports shouldn't be necessary. Its more an "investigative" feature I'd like to use to see when things start to go wrong. I'll have to wait for JuliaRobotics/RoME.jl#380 and JuliaRobotics/RoME.jl#378 anyways before performing the majority of experiments for my masters thesis :) Keep the work going on there :)

**Comment by dehann** [comment]
Hi @lemauee , jip -- we are definitely aware and working on it.  The fastest way to get you better results is to fix JuliaRobotics/IncrementalInference.jl#1051 first as shortest path to help on the RoME issues you listed, and the main event is JuliaRobotics/IncrementalInference.jl#1010 .  

The plan is to prioritize your issues in RoME, and 'break' some of our previous consolidation roadmap wrt to JuliaRobotics/ApproxManifoldProducts.jl#41.  Will return to that roadmap after IIF 1010.

BTW, your other JuliaRobotics/ApproxManifoldProducts.jl#45 will be much easier to do after JuliaRobotics/ApproxManifoldProducts.jl#41, which will only happen after IIF 1051, 1010.
