### ISSUE TITLE
Loading Error

### ISSUE THREAD

**Issue by guri-dominic** [JuliaRobotics/RoMEPlotting.jl#143]
I'm going through the basics examples in Caesar.jl and I have encountered this when I run `using RoMEPlotting`
```
ERROR: LoadError: LoadError: LoadError: parsing command 
`convert -delay $(delay) $(tmpfilepath)/$(string(lbll))mcmc*.png $(tmpfilepath)/$(string(lbll))mcmc.gif`: 
special characters "#{}()[]<>|&*?~;" must be quoted in commands
```
The error seems clear, and after playing in the REPL, I found the following
```
julia> typeof(a)
Cmd

julia> a = `ls`
`ls`
```
However, 
```
julia> a = `ls contact*`
ERROR: LoadError: parsing command `ls contact*`: special characters "#{}()[]<>|&*?~;" must be quoted in commands
```
The suggested fix `"*"`/`'*'` does not work
```
julia> a = `ls contact"*"`
`ls 'contact*'`

julia> run(a)
ls: cannot access 'contact*': No such file or directory
ERROR: failed process: Process(`ls 'contact*'`, ProcessExited(2)) [2]
```
I'm using Julia 1.5.0 on PopOS 20

**Comment by dehann** [comment]
Hi @guri-dominic , apologies for the slow reply -- things should be getting back online.

Which version of packages do you have, that sounds familiar to an older error perhaps... Thats from package manager, just type `status` and copy past here please.  Check that you have IncrementalInference.jl version 0.18 or above (v0.20.2 latest) and  RoME.jl v0.11 (v0.12.0 latest).

You should see a new release v0.5.1 soon (#148) which fixes an outdated compat in Project.toml.

**Comment by guri-dominic** [comment]
This was from v0.2.2. For some reason, RoMEPlotting wasn't updating (which I didn't notice at the time).
I had to update to Julia v1.5.3 to get RoMEPlotting v0.5.0

**Comment by dehann** [comment]
HI @guri-dominic , 

Just an FYI that RoMEPlotting v0.6.0 should be landing soon.  Thats with RoME v0.13.0 and Caesar v0.9.0 a little behind.  These are the latest versions as of today.  I will go ahead and close this issue.  Please reopen it if you are still experiencing this issue.

Best,
Dehann
