### ISSUE TITLE
Package fails on 1.5 due to incorrect command syntax

### ISSUE THREAD

**Issue by KristofferC** [JuliaRobotics/RoMEPlotting.jl#98]
The (since 0.7) deprecation warning

```
┌ Warning: Parsing command "convert -delay $(delay) $(tmpfilepath)/$(string(lbll))mcmc*.png $(tmpfilepath)/$(string(lbll))mcmc.gif". Special characters "#{}()[]<>|&*?~;" should now be quoted in commands
│   caller = shell_parse(::String, ::Bool; special::String) at shell.jl:107
```

was turned into an error in 1.5 and errors now in

https://github.com/JuliaRobotics/RoMEPlotting.jl/blob/0e60068debebf77f593946acc6795b1659333b2b/src/SolverVisualization.jl#L280

**Comment by dehann** [comment]
Hi @KristofferC , oh right thanks -- will fix.
