### ISSUE TITLE
BUG plotPose3Pairs function

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/RoMEPlotting.jl#99]
Think this should be deleted
https://github.com/JuliaRobotics/RoMEPlotting.jl/blob/0e60068debebf77f593946acc6795b1659333b2b/src/RobotViz.jl#L700-L707

**Comment by dehann** [comment]
Hi thanks, yeah there is a bug with `:x1` but not quite following why we should delete the whole function -- perhaps I'm missing something?  I'd rather update it...

**Comment by Affie** [comment]
Sorry for missing your reply, it seems to be duplicated, with the second one correct.

https://github.com/JuliaRobotics/RoMEPlotting.jl/blob/0e60068debebf77f593946acc6795b1659333b2b/src/RobotViz.jl#L700-L707

https://github.com/JuliaRobotics/RoMEPlotting.jl/blob/0e60068debebf77f593946acc6795b1659333b2b/src/RobotViz.jl#L794-L801

**Comment by Affie** [comment]
Looks fixed
